/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'tasks' : Array<Task>,
  'lastQuizScore' : [] | [bigint],
  'session' : SessionState,
  'profile' : [] | [UserProfile],
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface QuizQuestion { 'question' : string, 'answer' : string }
export interface QuizResult {
  'id' : bigint,
  'owner' : Principal,
  'date' : Time,
  'score' : bigint,
  'topics' : Array<string>,
  'questions' : Array<QuizQuestion>,
}
export interface SessionState {
  'timerSeconds' : bigint,
  'inStudyMode' : boolean,
  'currentReward' : boolean,
}
export type Status = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface StudyFile {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'owner' : Principal,
  'fileType' : string,
  'blobId' : string,
  'uploadedAt' : Time,
}
export interface Task {
  'id' : bigint,
  'status' : Status,
  'title' : string,
  'subject' : string,
  'owner' : Principal,
  'difficulty' : Difficulty,
  'createdAt' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'dailyGoal' : bigint,
  'completedToday' : bigint,
  'owner' : Principal,
  'createdAt' : Time,
  'language' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateUserProfile' : ActorMethod<[string, bigint], undefined>,
  'createTask' : ActorMethod<[string, string, Difficulty], bigint>,
  'deleteStudyFile' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getActiveQuiz' : ActorMethod<[], [] | [QuizResult]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getQuizHistory' : ActorMethod<[Principal], Array<QuizResult>>,
  'getSessionState' : ActorMethod<[Principal], SessionState>,
  'getStudyFiles' : ActorMethod<[], Array<StudyFile>>,
  'getStudyFilesBySubject' : ActorMethod<[string], Array<StudyFile>>,
  'getTasksForUser' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudyFile' : ActorMethod<[string, string, string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startQuiz' : ActorMethod<[Array<string>], bigint>,
  'submitQuiz' : ActorMethod<[bigint, bigint], undefined>,
  'updateSessionState' : ActorMethod<[SessionState], undefined>,
  'updateTask' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];