/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : Time,
  'score' : IDL.Nat,
  'topics' : IDL.Vec(IDL.Text),
  'questions' : IDL.Vec(QuizQuestion),
});
export const UserProfile = IDL.Record({
  'dailyGoal' : IDL.Nat,
  'completedToday' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'language' : IDL.Text,
});
export const Status = IDL.Variant({
  'done' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'owner' : IDL.Principal,
  'difficulty' : Difficulty,
  'createdAt' : Time,
});
export const SessionState = IDL.Record({
  'timerSeconds' : IDL.Nat,
  'inStudyMode' : IDL.Bool,
  'currentReward' : IDL.Bool,
});
export const DashboardSummary = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'lastQuizScore' : IDL.Opt(IDL.Nat),
  'session' : SessionState,
  'profile' : IDL.Opt(UserProfile),
});
export const StudyFile = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'owner' : IDL.Principal,
  'fileType' : IDL.Text,
  'blobId' : IDL.Text,
  'uploadedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateUserProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, Difficulty], [IDL.Nat], []),
  'deleteStudyFile' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getActiveQuiz' : IDL.Func([], [IDL.Opt(QuizResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getQuizHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuizResult)],
      ['query'],
    ),
  'getSessionState' : IDL.Func([IDL.Principal], [SessionState], ['query']),
  'getStudyFiles' : IDL.Func([], [IDL.Vec(StudyFile)], ['query']),
  'getStudyFilesBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudyFile)],
      ['query'],
    ),
  'getTasksForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudyFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startQuiz' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'submitQuiz' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateSessionState' : IDL.Func([SessionState], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : Time,
    'score' : IDL.Nat,
    'topics' : IDL.Vec(IDL.Text),
    'questions' : IDL.Vec(QuizQuestion),
  });
  const UserProfile = IDL.Record({
    'dailyGoal' : IDL.Nat,
    'completedToday' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'language' : IDL.Text,
  });
  const Status = IDL.Variant({
    'done' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'owner' : IDL.Principal,
    'difficulty' : Difficulty,
    'createdAt' : Time,
  });
  const SessionState = IDL.Record({
    'timerSeconds' : IDL.Nat,
    'inStudyMode' : IDL.Bool,
    'currentReward' : IDL.Bool,
  });
  const DashboardSummary = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'lastQuizScore' : IDL.Opt(IDL.Nat),
    'session' : SessionState,
    'profile' : IDL.Opt(UserProfile),
  });
  const StudyFile = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'owner' : IDL.Principal,
    'fileType' : IDL.Text,
    'blobId' : IDL.Text,
    'uploadedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateUserProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, Difficulty], [IDL.Nat], []),
    'deleteStudyFile' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getActiveQuiz' : IDL.Func([], [IDL.Opt(QuizResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getQuizHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuizResult)],
        ['query'],
      ),
    'getSessionState' : IDL.Func([IDL.Principal], [SessionState], ['query']),
    'getStudyFiles' : IDL.Func([], [IDL.Vec(StudyFile)], ['query']),
    'getStudyFilesBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudyFile)],
        ['query'],
      ),
    'getTasksForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudyFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startQuiz' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'submitQuiz' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateSessionState' : IDL.Func([SessionState], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };